### ISSUE TITLE
异常信息定制traceId，ps:我现在的traceId 是在header 里面存储的，如何定制???

### ISSUE THREAD

**Issue by bingLengDT** [guanguans/laravel-exception-notify#12]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by guanguans** [comment]
@bingLengDT 我没有明白你的意思。如果不想报告异常 `trace` 的信息可以在 `collector` 配置中修改 `exception_stack_trace`

```php
/*
 * Information collector.
 */
'collector' => [
    'app_name' => true,
    'app_env' => true,
    'trigger_time' => true,
    'request_method' => true,
    'request_url' => true,
    'request_ip' => true,
    'request_data' => true,
    'exception_stack_trace' => false, // 值为 false 不报告 `trace` 信息
],
```

**Comment by bingLengDT** [comment]
是这样：我想在多定制一个异常信息，就是traceId (相当于业务请求的唯一标识id),这个对我们多个微服务查询信息是比较方便的，类似下面截图这样

















在 2021-11-02 17:08:10，"guanguans" ***@***.***> 写道：

@bingLengDT 我没有明白你的意思。如果不想报告异常 trace 的信息可以在 collector 配置中修改 exception_stack_trace

/* * Information collector. */'collector' => [

    'app_name' => true,

    'app_env' => true,

    'trigger_time' => true,

    'request_method' => true,

    'request_url' => true,

    'request_ip' => true,

    'request_data' => true,

    'exception_stack_trace' => false, // 值为 false 不报告 `trace` 信息

],

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bingLengDT** [comment]
这个问题没有处理完毕，就关了呀？？？

**Comment by guanguans** [comment]
@bingLengDT 没有关闭这个问题。你的意思是当发生异常，顺便报告一个 traceId 的信息对吧，或者说可以报告一条扩展的额外信息信息对吗？

**Comment by bingLengDT** [comment]
是这个样子的



At 2021-11-02 18:32:13, "guanguans" ***@***.***> wrote:

@bingLengDT 没有关闭这个问题。你的意思是当发生异常，顺便报告一个 traceId 的信息对吧，或者说可以报告一条扩展的额外信息信息对吗？

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by guanguans** [comment]
@bingLengDT 最新版本已添加收集 `header` 信息，请更新至最新版本。

## 更新版本：

```shell
$ composer remove guanguans/laravel-exception-notify
$ composer require guanguans/laravel-exception-notify:^1.1.6
```

## 配置文件 `config/exception-notify.php` 的 `collector` 中添加：

```php
'collector' => [
    'app_name' => true,
    'app_env' => true,
    'trigger_time' => true,
    'request_method' => true,
    'request_url' => true,
    'request_ip' => true,
    'request_header' => true, // 添加
    'request_data' => true,
    'exception_stack_trace' => true,
],
```

**Comment by bingLengDT** [comment]
多谢~~~



在 2021-11-03 11:56:28，"guanguans" ***@***.***> 写道：

@bingLengDT 最新版本已添加收集 header 信息，请更新至最新版本。

更新版本：
$ composer remove guanguans/laravel-exception-notify

$ composer require guanguans/laravel-exception-notify:^1.1.6
配置文件 config/exception-notify.php 的 collector 中添加：
'collector' => [

    'app_name' => true,

    'app_env' => true,

    'trigger_time' => true,

    'request_method' => true,

    'request_url' => true,

    'request_ip' => true,

    'request_header' => true, // 添加'request_data' => true,

    'exception_stack_trace' => true,

],

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by guanguans** [comment]
@bingLengDT 客气了，应该的，有什么问题，尽量反馈过来。
