### ISSUE TITLE
希望能在这个地方增加trace的过滤

### ISSUE THREAD

**Issue by znmin** [guanguans/laravel-exception-notify#14]
希望能在这个地方增加trace的自定义过滤，比如包含 vendor 的信息过滤掉，因为企业微信的机器人消息是有长度限制，还是希望能尽可能提供自定义过滤

![image](https://user-images.githubusercontent.com/12841724/155927905-6b78961a-f7ff-4597-a5a0-fbee74229e44.png)

**Comment by guanguans** [comment]
以增加该功能，请尝试升级至 `1.2.3` 版本

## 配置

```php
...
// 可接受一个回调类型的变量去过滤 exception_stack_trace 信息
'exception_stack_trace' => function ($trace){
    return ! \Illuminate\Support\Str::contains($trace['file'], 'vendor');
},
...
```

**Comment by znmin** [comment]
> @znmin 已增加该功能，请尝试升级至 `1.2.3` 版本。
> 
> ## 配置
> ```
> ...
> // 可接受一个回调类型的变量去过滤 exception_stack_trace 信息
> 'exception_stack_trace' => function ($trace){
>     return ! \Illuminate\Support\Str::contains($trace['file'], 'vendor');
> },
> ...
> ```

太棒了，十分感谢！
