### ISSUE TITLE
Job错误

### ISSUE THREAD

**Issue by fangmuke** [guanguans/laravel-exception-notify#19]
![image](https://user-images.githubusercontent.com/26641510/160588845-e52c1f30-5f30-43f4-992f-5809518c3b10.png)
![image](https://user-images.githubusercontent.com/26641510/160588899-a0725ca1-de71-4fc6-aef6-9038fb3890e1.png)

Laravel Version: 9.4
PHP Version: 8.0

**Comment by guanguans** [comment]
@fangmuke 麻烦看一下 laravel 的具体版本，我去 [packagist](https://packagist.org/packages/laravel/laravel) 查看，没找到 `9.4` 版本。

**Comment by guanguans** [comment]
@fangmuke 我这边的环境是 `laravel framework version : 9.4.1`、`PHP version : 8.0.13`，没有复现出来。

**Comment by fangmuke** [comment]
> @fangmuke 我这边的环境是 `laravel framework version : 9.4.1`、`PHP version : 8.0.13`，没有复现出来。

我在本地也没有复现出来，不过现在可以肯定的是，传了一个null进去，所以报错了。
![image](https://user-images.githubusercontent.com/26641510/160741661-adc78264-6958-47f4-823e-c934174c210b.png)

**Comment by guanguans** [comment]
@fangmuke 看报错不是传了 null 值，应该是没有绑定 job 的 handle 方法参数成功，所以导致容器无法解析。可以看这段[代码](https://github.com/guanguans/laravel-exception-notify/blob/main/src/ExceptionNotifyManager.php#L69-L82):

![image](https://user-images.githubusercontent.com/22309277/160743780-1bccc3fc-3d14-4473-ad90-657a585aa6ac.png)

目前的解决方案是，不用 `绑定方法参数传递` report，通过构造函数传递应该就没什么问题了，不过还是不明白为什么没绑定成功，可以帮忙分析一下。

另外问一下您这边的队列默认驱动是什么？你这边有什么用命令行这种模式启动服务(swoole、workerman...)

**Comment by fangmuke** [comment]
> @fangmuke 看报错不是传了 null 值，应该是没有绑定 job 的 handle 方法参数成功，所以导致容器无法解析。可以看这段[代码](https://github.com/guanguans/laravel-exception-notify/blob/main/src/ExceptionNotifyManager.php#L69-L82):
> 
> ![image](https://user-images.githubusercontent.com/22309277/160743780-1bccc3fc-3d14-4473-ad90-657a585aa6ac.png)
> 
> 目前的解决方案是，不用 `绑定方法参数传递` report，通过构造函数传递应该就没什么问题了，不过还是不明白为什么没绑定成功，可以帮忙分析一下。
> 
> 另外问一下您这边的队列默认驱动是什么？你这边有什么用命令行这种模式启动服务(swoole、workerman...)

好的，使用的Redis驱动，没有用命令行模式启动，就是FPM。

**Comment by guanguans** [comment]
@fangmuke 我这边复现，且已经修复，请尝试更新到最新版本。

**Comment by fangmuke** [comment]
> @fangmuke 我这边复现，且已经修复，请尝试更新到最新版本。

好的，我试一下！

**Comment by fangmuke** [comment]
已解决，谢谢！
