### ISSUE TITLE
是否可以自动限流？

### ISSUE THREAD

**Issue by winter-ice** [guanguans/laravel-exception-notify#22]
**Is your feature request related to a problem? Please describe.**
一个异常触发时大概率会同时出发N个相同的异常，是否可以提供相应的解决方案？

**Describe the solution you'd like**
库可以自动检测异常，对短时间内相同的异常合并只报告一次。或者其他类似的主动限制功能。

**Describe alternatives you've considered**
或者可否提供思路在使用时解决该问题？

**Additional context**

**Comment by winter-ice** [comment]
类似功能参考：https://flareapp.io/docs/general/spike-protection

**Comment by guanguans** [comment]
@winter-ice 也可以用队列中间件来做？这个我们可以先探讨一下。再去实现。

**Comment by winter-ice** [comment]
具体方案我这边还没有想好，但是感觉这个需求还是有的，不然有时候触发一个bug，很多请求可能会在短时间触发数千数万个异常，而且再考虑到很多第三方通知api都有限流，超过限额就不让用了

**Comment by guanguans** [comment]
最新版本已支持速率限制
