### ISSUE TITLE
是否同步执行建议配置在文件exception-notify中

### ISSUE THREAD

**Issue by pgyf** [guanguans/laravel-exception-notify#25]
我想同步执行异常通知，但不影响项目中的队列配置。
建议可以优先读取exception-notify中的配置   这样就不影响项目原来的队列配置了
https://github.com/guanguans/laravel-exception-notify/blob/main/src/ExceptionNotifyManager.php#L95

**Comment by guanguans** [comment]
@pgyf 我抽个时间配置中加一下吧。

**Comment by pgyf** [comment]
@guanguans  好的 感谢！

**Comment by guanguans** [comment]
@pgyf 已支持请升级到最新版本。

**Comment by pgyf** [comment]
@guanguans 感谢 已经测试成功
