### ISSUE TITLE
控制台应用同步通知重启才能收到通知

### ISSUE THREAD

**Issue by pgyf** [guanguans/laravel-exception-notify#28]
https://github.com/guanguans/laravel-exception-notify/blob/0d4b032e5a04044aed1d0f8788e4b19bb68ae91c/src/ExceptionNotifyManager.php#L96

建议：如果在控制台中 不需要afterResponse

**Comment by guanguans** [comment]
抽时间优化一下。

**Comment by pgyf** [comment]
感谢！

**Comment by pgyf** [comment]
感谢！
