### ISSUE TITLE
钉钉机器人都不需要SECRET了

### ISSUE THREAD

**Issue by wumahoo** [guanguans/laravel-exception-notify#29]
钉钉机器人的配置，还需要 SECRET ？

**Comment by guanguans** [comment]
有时间我改一下。

**Comment by guanguans** [comment]
> 钉钉机器人的配置，还需要 SECRET ？

@wumahoo `SECRET` 是一个可选的配置，并不是不需要这个配置。相关文档 ：[https://open.dingtalk.com/document/robots/customize-robot-security-settings](https://open.dingtalk.com/document/robots/customize-robot-security-settings)
