### ISSUE TITLE
钉钉的token  secret keyword是在哪里获取的啊?

### ISSUE THREAD

**Issue by uniteweiwei** [guanguans/laravel-exception-notify#32]
先要成为开发者?然后去创建应用,但是创建应用之后,拿不到这三个参数啊,具体是创建什么应用才能拿到?
![image](https://user-images.githubusercontent.com/19373139/224476163-36a16d28-6ca0-48c3-ae3c-87856e9e6691.png)

**Comment by guanguans** [comment]
https://open.dingtalk.com/document/orgapp/custom-robot-access

**Comment by uniteweiwei** [comment]
没有找到,只有一个webhook
![image](https://user-images.githubusercontent.com/19373139/224476530-b6f57df3-a404-458e-a17c-8b5d7a9c875b.png)

**Comment by uniteweiwei** [comment]
![image](https://user-images.githubusercontent.com/19373139/224476554-4ecd2bb0-9d62-403b-bc47-3fca78c87cd7.png)
还有一个加签的
