### ISSUE TITLE
vscode打开项目提示如下错误

### ISSUE THREAD

**Issue by zwping** [guanguans/laravel-exception-notify#55]
`laravel 10.33` `laravel-exception-notify 3.5.0`
```
"Exception Basic": {
        "class": "Symfony/Component/Console/Exception/RuntimeException",
        "message": "The /"--columns/" option does not exist.",
        "code": 0,
        "file": "vendor/symfony/console/Input/ArgvInput.php",
        "line": 223
    },
    "Exception Context": {
        "  214": "    /**",
        "  215": "     * Adds a long option value.",
        "  216": "     *",
        "  217": "     * @throws RuntimeException When option given doesn't exist",
        "  218": "     */",
        "  219": "    private function addLongOption(string $name, mixed $value): void",
        "  220": "    {",
        "  221": "        if (!$this->definition->hasOption($name)) {",
        "  222": "            if (!$this->definition->hasNegation($name)) {",
        "➤ 223": "                throw new RuntimeException(sprintf('The /"--%s/" option does not exist.', $name));",
        "  224": "            }",
        "  225": "",
        "  226": "            $optionName = $this->definition->negationToName($name);",
        "  227": "            if (null !== $value) {",
        "  228": "                throw new RuntimeException(sprintf('The /"--%s/" option does not accept a value.', $name));",
        "  229": "            }",
        "  230": "            $this->options[$optionName] = false;",
        "  231": "",
        "  232": "            return;",
        "  233": "        }"
    },
    "Exception Trace": {
        "10": "#10 artisan(35): Illuminate/Foundation/Console/Kernel->handle(Object(Symfony/Component/Console/Input/ArgvInput), Object(Symfony/Component/Console/Output/ConsoleOutput))",
        "11": "#11 {main}"
    },
```

**Comment by guanguans** [comment]
@zwping 这是正常的吧。你去看laravel的错误日志去看响应的错误。

**Comment by zwping** [comment]
非正常吧，很尬的现象是，每次启动项目通知一下异常群？

**Comment by zwping** [comment]
这是完整的日志，目前将其加入了except避免了这个现象

**Comment by zwping** [comment]
大佬能否剖析下vs启动laravel的过程，优化下这个现象？

**Comment by guanguans** [comment]
> 非正常吧，很尬的现象是，每次启动项目通知一下异常群？

大概是因为vscode启动的时候执行了一些错误的命令或者什么，行为默认是laravel的报错保持一致的，laravel里面有报错，这里就有报错提醒了。

最简单可以仅配置生产或者测试环境就好了，或者排除掉你那个具体异常的报告。

```php
<?php

return [
	...

    /**
     * The list of environments that should be reported.
     */
    'env' => env_explode('EXCEPTION_NOTIFY_ENV', [
        'production',
        // 'local',
        'testing',
        // '*',
    ]),

    /**
     * The list of exception that should not be reported.
     */
    'except' => [
		// 那个具体的异常类
        // Illuminate\Http\Exceptions\HttpResponseException::class,
    ],
	...
];
```

**Comment by zwping** [comment]
ok

**Comment by Dibbyo456** [comment]
Having the exact same issue. Opening vscode causing notification to trigger.

```
[2024-01-21 12:12:36] local.ERROR: The "--columns" option does not exist. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\RuntimeException(code: 0): The \"--columns\" option does not exist. at /Users/harry/Projects/laratest/vendor/symfony/console/Input/ArgvInput.php:223)
[stacktrace]
#0 /Users/harry/Projects/laratest/vendor/symfony/console/Input/ArgvInput.php(150): Symfony\\Component\\Console\\Input\\ArgvInput->addLongOption('columns', 'name,action')
#1 /Users/harry/Projects/laratest/vendor/symfony/console/Input/ArgvInput.php(85): Symfony\\Component\\Console\\Input\\ArgvInput->parseLongOption('--columns=name,...')
#2 /Users/harry/Projects/laratest/vendor/symfony/console/Input/ArgvInput.php(74): Symfony\\Component\\Console\\Input\\ArgvInput->parseToken('--columns=name,...', true)
#3 /Users/harry/Projects/laratest/vendor/symfony/console/Input/Input.php(56): Symfony\\Component\\Console\\Input\\ArgvInput->parse()
#4 /Users/harry/Projects/laratest/vendor/symfony/console/Command/Command.php(285): Symfony\\Component\\Console\\Input\\Input->bind(Object(Symfony\\Component\\Console\\Input\\InputDefinition))
#5 /Users/harry/Projects/laratest/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#6 /Users/harry/Projects/laratest/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 /Users/harry/Projects/laratest/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Foundation\\Console\\RouteListCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#8 /Users/harry/Projects/laratest/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 /Users/harry/Projects/laratest/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#10 /Users/harry/Projects/laratest/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#11 {main}
"} 
```

**Comment by guanguans** [comment]
> Having the exact same issue. Opening vscode causing notification to trigger.
> 
> ```
> [2024-01-21 12:12:36] local.ERROR: The "--columns" option does not exist. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\RuntimeException(code: 0): The \"--columns\" option does not exist. at /Users/harry/Projects/laratest/vendor/symfony/console/Input/ArgvInput.php:223)
> [stacktrace]
> #0 /Users/harry/Projects/laratest/vendor/symfony/console/Input/ArgvInput.php(150): Symfony\\Component\\Console\\Input\\ArgvInput->addLongOption('columns', 'name,action')
> #1 /Users/harry/Projects/laratest/vendor/symfony/console/Input/ArgvInput.php(85): Symfony\\Component\\Console\\Input\\ArgvInput->parseLongOption('--columns=name,...')
> #2 /Users/harry/Projects/laratest/vendor/symfony/console/Input/ArgvInput.php(74): Symfony\\Component\\Console\\Input\\ArgvInput->parseToken('--columns=name,...', true)
> #3 /Users/harry/Projects/laratest/vendor/symfony/console/Input/Input.php(56): Symfony\\Component\\Console\\Input\\ArgvInput->parse()
> #4 /Users/harry/Projects/laratest/vendor/symfony/console/Command/Command.php(285): Symfony\\Component\\Console\\Input\\Input->bind(Object(Symfony\\Component\\Console\\Input\\InputDefinition))
> #5 /Users/harry/Projects/laratest/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
> #6 /Users/harry/Projects/laratest/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
> #7 /Users/harry/Projects/laratest/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Foundation\\Console\\RouteListCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
> #8 /Users/harry/Projects/laratest/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
> #9 /Users/harry/Projects/laratest/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
> #10 /Users/harry/Projects/laratest/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
> #11 {main}
> "} 
> ```

My guess is that some plugin or something executed some wrong command or something when vscode started up. The default behavior is consistent with the error reported by Laravel. There is an error reported in Laravel, so here is the error alert.

It is best to check what error commands are executed every time your editor starts.

You can also configure only the production or testing environment, or exclude your specific exception report.

```php
<?php

return [
	...
    'env' => env_explode('EXCEPTION_NOTIFY_ENV', [
        'production',
        // 'local',
        'testing',
        // '*',
    ]),
    
    'except' => [
		// The exception class
        // Symfony\Component\Console\Exception\RuntimeException::class,
    ],
	...
];
```

**Comment by Dibbyo456** [comment]
> My guess is that some plugin or something executed some wrong command or something when vscode started up.

Found the culprit, it is causing by [Laravel Goto](https://marketplace.visualstudio.com/items?itemName=absszero.vscode-laravel-goto) extension.

**Comment by Dibbyo456** [comment]
This is fixed now. You can close it.
