### ISSUE TITLE
Call to undefined method NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler::reportable()

### ISSUE THREAD

**Issue by gyp719** [guanguans/laravel-exception-notify#66]
php8.1 

laravel 10

<img width="1202" alt="image" src="https://github.com/guanguans/laravel-exception-notify/assets/30563368/cb0b24bc-1c96-44c2-8c6d-0d3a6bc603ef">

**Comment by guanguans** [comment]
@gyp719 guanguans/laravel-exception-notify 版本是多少？
更新到最新版本试试。

**Comment by gyp719** [comment]
是的， 已解决。
