### ISSUE TITLE
企业微信的 EXCEPTION_NOTIFY_WEWORK_TOKEN 在哪里获取？

### ISSUE THREAD

**Issue by gyp719** [guanguans/laravel-exception-notify#67]
请教下，企业微信的 EXCEPTION_NOTIFY_WEWORK_TOKEN 在哪里获取？

<img width="1296" alt="image" src="https://github.com/guanguans/laravel-exception-notify/assets/30563368/021528b6-d634-4770-8706-253911052c34">

**Comment by guanguans** [comment]
@gyp719 [guanguans/notify](https://github.com/guanguans/notify) 中有对应的官方文档地址([src/WeWork/README.md](https://github.com/guanguans/notify/blob/main/src/WeWork/README.md))。

企业微信群机器人 webhook 中的 key 就是。

**Comment by gyp719** [comment]
> @gyp719 [guanguans/notify](https://github.com/guanguans/notify) 中有对应的官方文档地址([src/WeWork/README.md](https://github.com/guanguans/notify/blob/main/src/WeWork/README.md))。
> 
> 企业微信群机器人 webhook 中的 key 就是。

看待这个文档了， 但是企业机器人没有显示 webhook

<img width="1245" alt="image" src="https://github.com/guanguans/laravel-exception-notify/assets/30563368/33dfe6fe-5bec-4f38-9ab4-66f4c5e1f684">

**Comment by gyp719** [comment]
可以了

**Comment by guanguans** [comment]
@gyp719 你截图的是应用机器人，不是群机器人。

https://open.work.weixin.qq.com/help2/pc/14931?person_id=1&is_tencent=
