### ISSUE TITLE
Laravel执行安装后post-autoload-dump报错

### ISSUE THREAD

**Issue by czhou** [guanguans/laravel-exception-notify#69]
**Describe the bug**
执行 composer require guanguans/laravel-exception-notify --ansi -v 后：
>Generating optimized autoload files
> post-autoload-dump: Illuminate\Foundation\ComposerScripts::postAutoloadDump
PHP Fatal error:  Cannot redeclare make() (previously declared in /var/www/html/vendor/guanguans/laravel-exception-notify/src/Support/helpers.php:28) in /var/www/html/tests/helpers.php on line 10

>Fatal error: Cannot redeclare make() (previously declared in /var/www/html/vendor/guanguans/laravel-exception-notify/src/Support/helpers.php:28) in /var/www/html/tests/helpers.php on line 10

**Additional context**
Laravel：v8.83.27
PHP: v8.1
laravel-exception-notify: v4.5.1

**Comment by czhou** [comment]
找到原因了，因为我在我的单元测试辅助脚本中定义了一个make函数，所以和你的包中同名make函数冲突了。
![image](https://github.com/user-attachments/assets/826dfc99-f10b-40b4-95a1-a9e3aec42ed1)

但是这个问题是不是你们也应该修改一下，make这个函数名还是比较容易起冲突的...
![image](https://github.com/user-attachments/assets/b288b668-a99e-4f18-9209-03602386bc88)

**Comment by guanguans** [comment]
@czhou 我先记下，等下一个大版本处理。你那边测试专用的先加上测试的命名空间。
