### ISSUE TITLE
有个想法：在队列中执行报警通知

### ISSUE THREAD

**Issue by PrintNow** [guanguans/laravel-exception-notify#8]
但我这么使用好像没效果

`app/Exceptions/Handler.php`

```php
    public function report(Throwable $e)
    {
        if($this->shouldReport($e)){
            Log::info('我来到');
            ExceptionsJob::dispatch($e);
        }

        parent::report($e);
    }
```

`ExceptionsJob.php`

```php
<?php

namespace App\Jobs\Core;

use ExceptionNotifier;
use Guanguans\LaravelExceptionNotify\Facades\Notifier;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldBeUnique;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Throwable;

class ExceptionsJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct(public Throwable $e)
    {
        $this->queue = 'core-exceptions';
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        // Notifier::report($this->e);
        app('exception.notifier')->report($this->e);
    }
}

```

**Comment by guanguans** [comment]
@PrintNow 已经使用队列去通知了，相关代码：

[https://github.com/guanguans/laravel-exception-notify/blob/main/src/Notifier.php#L99-L119](https://github.com/guanguans/laravel-exception-notify/blob/main/src/Notifier.php#L99-L119)

[https://github.com/guanguans/laravel-exception-notify/blob/main/src/Jobs/SendExceptionNotification.php](https://github.com/guanguans/laravel-exception-notify/blob/main/src/Jobs/SendExceptionNotification.php)

**Comment by guanguans** [comment]
@PrintNow 是用的异步。

**Comment by PrintNow** [comment]
@guanguans 我需要做什么操作去启动这个队列吗，因为我发现我没有启动任何队列，报错通知 还是能够推送到钉钉机器人

**Comment by guanguans** [comment]
@PrintNow 我这边刚测试了一下是有的，你可以重启一下服务再试试。

![image](https://user-images.githubusercontent.com/22309277/136538872-59c009fe-50dd-4538-a986-16e824f29682.png)

**Comment by PrintNow** [comment]
@guanguans 

就改动了这个文件 `/app/Exceptions/Handler.php`，增加了 `report` 方法

```php
<?php

namespace App\Exceptions;

use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that are not reported.
     *
     * @var array
     */
    protected $dontReport = [
        //
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     *
     * @return void
     */
    public function register()
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }

    /**
     * 异常报告
     *
     * @param \Throwable $e
     *
     * @throws \Throwable
     */
    public function report(Throwable $e)
    {
        // 新增了这2句
        $this->shouldReport($e) and \Guanguans\LaravelExceptionNotify\Facades\Notifier::report($e);
        parent::report($e);
    }
}

```

**Comment by PrintNow** [comment]
@guanguans 找到相关类似的问题：https://laracasts.com/discuss/channels/laravel/dispatch-a-job-5-minutes-after-json-response

> You cannot delay in the same thread, or as you have found, it just hangs your application
> 
> The correct way is to queue the job then run a queue worker that will pickup the job and send the notification.
> 
> https://laravel.com/docs/8.x/queues#introduction
> 
> and
> 
> https://laravel.com/docs/8.x/queues#delayed-dispatching
> 
> Note that you have to setup your queues first as out of the box it uses sync as the queue driver which means process the queue immediately (in the same thread). You need to use database, redis or one of the other queue drivers

**Comment by PrintNow** [comment]
@guanguans 我直接把这代码注释 `method_exists($dispatch, 'afterResponse') && $dispatch->afterResponse();` 然后提交吗？

另外：
> 没记错的话，只要 `.env` 文件里配置的是 `QUEUE_CONNECTION=sync`，然后派遣任务，任务就会同步执行。

**Comment by PrintNow** [comment]
@guanguans 验证了下我刚刚说的，的确就是这样的，那我提交个 PR
> 没记错的话，只要 .env 文件里配置的是 QUEUE_CONNECTION=sync，然后派遣任务，任务就会同步执行。

**Comment by guanguans** [comment]
@PrintNow 这样子改吧。如果是同步就还是按之前的响应之后再通知报错：

```php
config('queue.default') === 'sync' and method_exists($dispatch, 'afterResponse') and $dispatch->afterResponse();
```

**Comment by PrintNow** [comment]
@guanguans 已发送邮件，能加上 dalao 微信，荣幸至极

**Comment by guanguans** [comment]
@PrintNow 这个 bug 麻烦你了，我自己都没发现。已加你好友😃。
